steps:
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   entrypoint: gcloud
  #   args:
  #     - auth
  #     - application-default
  #     - login
  #     - --scopes
  #     - https://www.googleapis.com/auth/siteverification.verify_only,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/sqlservice.login,openid
  - id: tf plan
    name: hashicorp/terraform:1.9.5
    entrypoint: sh
    args:
      - -c
      - |
        apk add --no-cache curl bash nodejs npm
        curl -sL https://taskfile.dev/install.sh | sh
        mv ./bin/task /usr/local/bin/task
        task --version

        npm install -g pnpm
        pnpm --version

        npm install -g typescript
        tsc --version

        # Authenticate with gcloud and set scopes
        echo $SERVICE_ACCOUNT_KEY > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json
        gcloud auth application-default login --scopes=https://www.googleapis.com/auth/siteverification.verify_only,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/sqlservice.login,openid

        # Run the Taskfile command
        task terraform-apply
    secretEnv: ['SERVICE_ACCOUNT_KEY']

secrets:
  # - kmsKeyName: projects/pras-sandbox-405410/locations/global/keyRings/YOUR_KEYRING/cryptoKeys/YOUR_KEY
  - secretEnv:
      SERVICE_ACCOUNT_KEY: projects/630923649102/secrets/terraform-cloudbuild-sa-service-account/versions/latest
