steps:
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   entrypoint: gcloud
  #   args:
  #     - auth
  #     - application-default
  #     - login
  #     - --scopes
  #     - https://www.googleapis.com/auth/siteverification.verify_only,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/sqlservice.login,openid
  - id: tf plan
    name: hashicorp/terraform:1.9.5
    entrypoint: sh
    args:
      - -c
      - |
        apk add --no-cache curl bash
        curl -sL https://taskfile.dev/install.sh | sh
        mv ./bin/task /usr/local/bin/task
        task --version

        npm install -g pnpm
        pnpm --version

        task terraform-apply
