steps:
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   entrypoint: gcloud
  #   args:
  #     - auth
  #     - application-default
  #     - login
  #     - --scopes
  #     - https://www.googleapis.com/auth/siteverification.verify_only,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/sqlservice.login,openid
  - name: alpine
    entrypoint: sh
    args:
      - -c
      - |
        apk add --no-cache curl bash
        curl -sL https://taskfile.dev/install.sh | sh
        mv ./bin/task /usr/local/bin/task
        task --version
  - id: tf plan
    name: hashicorp/terraform:1.9.5
    entrypoint: sh
    args:
      - -c
      - |
        task terraform-apply
  # - id: tf plan
  #   name: hashicorp/terraform:1.9.5
  #   entrypoint: sh
  #   args:
  #     - -c
  #     - |
  #       terraform -chdir=terraform init \
  #         -backend-config="bucket=xplorers-backend" \
  #         -backend-config="prefix=terraform/state"
  #       terraform -chdir=terraform apply -auto-approve \
  #         -var "project_id=pras-sandbox-405410" \
  #         -var "region=us-central1" \
  #         -var "zone=us-central1-c" \
  #         -var "project_number=630923649102" \
  #         -var "backend_bucket_name=xplorers-backend" \
  #         -var "static_ai_website_bucket_name=xplorers.learnwithpras.xyz"
